amazon:
  associateId: habuma-20



management:
  endpoints:
    shutdown:
      id: kill
    metrics:
      enabled: false
    web:
      exposure:
        include: beans, conditions, mappings, health, info, env, metrics